DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS url_check;

CREATE TABLE IF NOT EXISTS urls (
    id IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS url_check (
    id IDENTITY PRIMARY KEY,
    url_id BIGINT NOT NULL,
    codeAnswer INT,
    title TEXT,
    h1 TEXT,
    description TEXT,
    dateCheck TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE
);